Pagoda/Controllers/DetailFamilyController.cs
using DocumentFormat.OpenXml.Drawing.Charts;
using DocumentFormat.OpenXml.Office2010.Excel;
using PagedList;
using Pagoda.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Linq;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using System.Xml;

namespace Pagoda.Controllers
{
    public class DetailFamilyController : Controller
    {
        // GET: DetailFamily
        [CheckLogin]

        public ActionResult Index(string keywords, Family family, int? page, string sortOrder, string searchString, string currentFilter)
        {
            string connectionString = ConfigurationManager.ConnectionStrings["PagodaConnectionString1"].ConnectionString;
            PagodaDataContext context = new PagodaDataContext(connectionString);

            IEnumerable<DetailFamily> dsDetailFamily = context.DetailFamilies.Where(x => x.FamilyID == family.FamilyID).ToList();

            TempData["FamilyID"] = family.FamilyID.ToString();
            TempData["FamilyName"] = family.FamilyName;
            TempData["FamilyAddress"] = family.Address;

            ViewBag.CurrentSort = sortOrder;
            ViewBag.FullNameSort = String.IsNullOrEmpty(sortOrder) ? "fullname_desc" : "";
            ViewBag.AgeSort = sortOrder == "Age" ? "age_desc" : "Age";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            if (!String.IsNullOrEmpty(searchString))
            {
                dsDetailFamily = dsDetailFamily.Where(s => s.FullName.ToLower().Contains(searchString.ToLower()));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    dsDetailFamily = dsDetailFamily.OrderByDescending(s => s.FullName.Substring(s.FullName.LastIndexOf(" ") + 1));
                    break;
                case "Age":
                    dsDetailFamily = dsDetailFamily.OrderBy(s => s.Age);
                    break;
                case "age_desc":
                    dsDetailFamily = dsDetailFamily.OrderByDescending(s => s.Age);
                    break;
                default:  // Name ascending 
                    dsDetailFamily = dsDetailFamily.OrderBy(s => s.FullName.Substring(s.FullName.LastIndexOf(" ") + 1));
                    break;
            }

            int pageSize = 999999;
            int pageNumber = (page ?? 1);
            return View(dsDetailFamily.ToPagedList(pageNumber, pageSize));
        }


        [HttpGet]
        public PartialViewResult Create()   //Insert PartialView  
        {
            return PartialView(new Pagoda.Models.DetailFamily());
        }


        [HttpPost]
        public JsonResult Create(DetailFamily detailFamily, Family family, string fullFamilyName) // Record Insert  
        {
            string connectionString = ConfigurationManager.ConnectionStrings["PagodaConnectionString1"].ConnectionString;
            PagodaDataContext context = new PagodaDataContext(connectionString);

            var star = context.Stars.FirstOrDefault(x => x.Age == detailFamily.Age && x.Sex == detailFamily.Sex);
            if (star == null)
            {
                detailFamily.Star = star ?? null;
            }
            else
            {
                detailFamily.Star = star;
            }

            var threat = context.Threats.FirstOrDefault(x => x.Age == detailFamily.Age && x.Sex == detailFamily.Sex);
            if (threat == null)
            {
                detailFamily.Threat = threat ?? null;
            }
            else
            {
                detailFamily.Threat = threat;
            }

            fullFamilyName = family.FamilyID.ToString();

            ViewBag.fullFamilyName = fullFamilyName;

            //detailFamily.YearUser = (DateTime.Now.Year - detailFamily.Age) + 1;

            context.DetailFamilies.InsertOnSubmit(detailFamily);
            context.SubmitChanges();

            TempData["Message"] = "Dữ liệu của bạn đã được tạo thành công!!";

            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }


        public ActionResult Delete(string DetailFamilyID)
        {
            string connectionString = ConfigurationManager.ConnectionStrings["PagodaConnectionString1"].ConnectionString;
            PagodaDataContext context = new PagodaDataContext(connectionString);
            DetailFamily detailFamily = context.DetailFamilies.FirstOrDefault(x => x.DetailFamilyID.ToString() == DetailFamilyID);

            context.DetailFamilies.DeleteOnSubmit(detailFamily);
            context.SubmitChanges();
            TempData["Message"] = "Dữ liệu của bạn đã được xóa thành công!!";

            Family family = new Family();

            return RedirectToAction("Index", new { FamilyID = detailFamily.FamilyID.ToString() });
        }


        [HttpPost]
        public ActionResult DeleteAll(string ids)
        {
            string connectionString = ConfigurationManager.ConnectionStrings["PagodaConnectionString1"].ConnectionString;
            PagodaDataContext context = new PagodaDataContext(connectionString);
            if (!string.IsNullOrEmpty(ids))
            {
                var items = ids.Split(',').Select(x => Convert.ToInt32(x)).ToList();
                if (items != null && items.Any())
                {
                    var DetailFamilyToDelete = context.DetailFamilies.Where(x => items.Contains(x.DetailFamilyID)).ToList();
                    context.DetailFamilies.DeleteAllOnSubmit(DetailFamilyToDelete);
                    TempData["Message"] = "Tất Cả dữ liệu của bạn đã được xóa thành công!!";
                    context.SubmitChanges();
                }
                return Json(new { success = true });
            }
            return Json(new { success = false });
        }


        [HttpGet]
        public PartialViewResult Edit(Int32 DetailFamilyID)  // Update PartialView  
        {
            string connectionString = ConfigurationManager.ConnectionStrings["PagodaConnectionString1"].ConnectionString;
            PagodaDataContext context = new PagodaDataContext(connectionString);
            DetailFamily detailFamily = context.DetailFamilies.Where(x => x.DetailFamilyID == DetailFamilyID).FirstOrDefault();
            DetailFamily detailFamilys = new DetailFamily();

            detailFamilys.DetailFamilyID = detailFamily.DetailFamilyID;
            detailFamilys.FullName = detailFamily.FullName;
            detailFamilys.Age = detailFamily.Age;
            detailFamilys.Sex = detailFamily.Sex;

            return PartialView(detailFamilys);
        }


        [HttpPost]
        public JsonResult Edit(DetailFamily detailFamily, Family family, string fullFamilyName)
        {
            string connectionString = ConfigurationManager.ConnectionStrings["PagodaConnectionString1"].ConnectionString;
            PagodaDataContext context = new PagodaDataContext(connectionString);
            DetailFamily df = context.DetailFamilies.Where(x => x.DetailFamilyID == detailFamily.DetailFamilyID).FirstOrDefault();

            fullFamilyName = family.FamilyID.ToString();

            ViewBag.fullFamilyName = fullFamilyName;

            df.FullName = detailFamily.FullName;
            df.Age = detailFamily.Age;
            df.Sex = detailFamily.Sex;

            var star = context.Stars.FirstOrDefault(x => x.Age == detailFamily.Age && x.Sex == detailFamily.Sex);
            if (star == null)
            {
                df.Star = star ?? null;
            }
            else
            {
                df.Star = star;
            }

            var threat = context.Threats.FirstOrDefault(x => x.Age == detailFamily.Age && x.Sex == detailFamily.Sex);
            if (threat == null)
            {
                df.Threat = threat ?? null;
            }
            else
            {
                df.Threat = threat;
            }

            context.SubmitChanges();
            TempData["Message"] = "Dữ liệu của bạn đã được cập nhật thành công!!";
            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }


        public ActionResult Details(string DetailFamilyID, string fullname, Family family)
        {
            string connectionString = ConfigurationManager.ConnectionStrings["PagodaConnectionString1"].ConnectionString;
            PagodaDataContext context = new PagodaDataContext(connectionString);
            DetailFamily detailFamily = context.DetailFamilies.FirstOrDefault(x => x.DetailFamilyID.ToString() == DetailFamilyID);
            fullname = family.FamilyID.ToString();
            ViewBag.fullname = fullname;
            return View(detailFamily);
        }

        public ActionResult List(int? familyID, Family family, string sortOrder)
        {
            string connectionString = ConfigurationManager.ConnectionStrings["PagodaConnectionString1"].ConnectionString;
            PagodaDataContext context = new PagodaDataContext(connectionString);

            IEnumerable<DetailFamily> dsDetailFamily = context.DetailFamilies.Where(x => x.FamilyID == familyID).ToList();

            if (familyID == null)
            {
                return RedirectToAction("Index", "Home");
            }

            ViewBag.FamilyName = context.Families.FirstOrDefault(x => x.FamilyID == familyID)?.FamilyName;

            ViewBag.Address = context.Families.FirstOrDefault(x => x.FamilyID == familyID)?.Address;

            switch (sortOrder)
            {
                default:  // Name ascending 
                    dsDetailFamily = dsDetailFamily.OrderBy(s => s.FullName.Substring(s.FullName.LastIndexOf(" ") + 1));
                    break;
            }

Pagoda/Views/DetailFamily/Index.cshtml
@model PagedList.PagedList<Pagoda.Models.DetailFamily>
@using PagedList.Mvc;
@using PagedList;

@{
    ViewBag.Title = "Danh Sách Thành Viên Gia Đình";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section naviheader{
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
    </ul>
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Quản Lý Cầu An</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/Family">Quản Lý Cầu An</a></li>
                    <li class="breadcrumb-item active">@ViewBag.Title</li>
                </ol>
            </div>
        </div>
        <div class="row mb-2">
            <div class="col-sm-8">
                <form class="form-inline">
                    @using (Html.BeginForm("Index", "DetailFamily", FormMethod.Get))
                    {
                        @Html.Hidden("FamilyID", TempData["FamilyID"])
                        @Html.TextBox("searchString", ViewBag.CurrentFilter as string, new { @class = "form-control", @id = "Search", placeholder = "Nhập họ tên thành viên cần tìm kiếm ...", @style = "max-width: 500px; width: 60%" })
                        <button class="btn btn-info ml-1" type="submit">Tìm kiếm</button>
                    }
                </form>
            </div>
            <div align="right" class="col-sm-4">
                <div class="btn-group mr-1">
                    <div class="btn mr-1 p-0">
                        @using (Html.BeginForm("PrintPDF", "DetailFamily", FormMethod.Post))
                        {
                            @Html.Hidden("FamilyID", TempData["FamilyID"])
                            @Html.Hidden("FamilyName", TempData["FamilyName"])
                            <button type="submit" class="btn" style="float: right; color: white; background-color: #6600FF">In Danh Sách</button>
                        }
                    </div>
                    <div class="btn p-0">
                        <form action="/DetailFamily" method="post" id="form-detail-family">
                            <input type="hidden" name="FamilyID" value="@TempData["FamilyID"]" />
                            <button class="btn mr-1" style="float: right; background-color: #CD853F; color: white" type="button" onclick="submitForm()">Làm Mới Danh Sách</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

@if (TempData["Message"] != null)
{
    <div class="alert alert-default-info" style="margin-left: 8px; margin-right: 8px">
        @TempData["Message"]
        <button type="button" class="close" data-dismiss="alert">
            <span>
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="25" style="vertical-align: unset" fill="currentColor" class="bi bi-x-circle-fill" viewBox="0 0 16 16">
                    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM5.354 4.646a.5.5 0 1 0-.708.708L7.293 8l-2.647 2.646a.5.5 0 0 0 .708.708L8 8.707l2.646 2.647a.5.5 0 0 0 .708-.708L8.707 8l2.647-2.646a.5.5 0 0 0-.708-.708L8 7.293 5.354 4.646z" />
                </svg>
            </span>
        </button>
    </div>
}

<div id="OpenDilog">

</div>

<section class="content">
    <!-- Default box -->
    <div class="card">
        <div class="card-header" style="position: relative;">
            <h3 class="card-title" style="position: absolute; top: 35%;">
                Danh sách thành viên gia đình
                @*của <b>@TempData["FamilyName"]</b>*@
            </h3>

            <div align="right" class="card-tools d-flex">
                @*@Html.ActionLink("Thêm Mới", "Create", new { FamilyID = @TempData["FamilyID"] }, new { @class = "btn", @style = "background-color: #000066; color: white" })*@

                <a href="#" class="btn mr-1" style="background-color: #000066; color: white" onclick="CreateDetailFamily('@TempData["FamilyID"]')">
                    Thêm Mới
                </a>
                <input type="submit" id="btnDeleteAll" class="btn btn-danger" value="Xóa Tất Cả" />
            </div>

        </div>
        <div class="card-body" style="overflow-y: scroll; height: 500px;">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th style="text-align: center"><input type="checkbox" id="SelectAll" class="cbkSelectAll" /></th>

                        <th style="text-align: center">STT</th>
                        <th style="text-align: center">
                            Họ Tên
                        </th>
                        <th style="text-align: center">
                            Tuổi
                        </th>
                        <th style="text-align: center">Giới Tính</th>
                        <th style="text-align: center">Sao Chiếu Mệnh</th>
                        <th style="text-align: center">Hạn Kiết Hung</th>
                        <th style="text-align: center">Hành Động</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null && Model.Any())
                    {
                        var i = 1;
                        foreach (var item in Model)
                        {
                            <tr id="trow_@item.DetailFamilyID" class="Search">
                                <td style="text-align: center"><input type="checkbox" class="cbkItem" value="@item.DetailFamilyID" /></td>

                                <td style="text-align: center">@i</td>
                                <td style="text-align: center">@item.FullName</td>
                                <td style="text-align: center">@item.Age</td>
                                <td style="text-align: center">
                                    @if (item.Sex == true)
                                    {
                                        @Html.Raw("Nam")
                                    }
                                    else if (item.Sex == false)
                                    { @Html.Raw("Nữ")}
                                </td>
                                <td style="text-align: center">
                                    @if (item.Star != null)
                                    {
                                        @item.Star.StarName
                                    }
                                </td>
                                <td style="text-align: center">
                                    @if (item.Threat != null)
                                    {
                                        @item.Threat.ThreatName
                                    }
                                </td>

                                <td style="text-align: center">

                                    <a href="#" class="btn btn-sm btn-success" onclick="EditDetailFamily('@item.DetailFamilyID')">
                                        Chỉnh Sửa
                                    </a>

                                    @Html.ActionLink("Xóa", "Delete", new { DetailFamilyID = item.DetailFamilyID }, new { @class = "btn btn-sm btn-warning", onclick = "return confirm('Bạn có chắc chắn muốn xóa không?');" })
                                </td>
                            </tr>
                            i++;
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="12">Không có bản ghi nào!!!</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</section>

<style>
    .my-dialog-class {
        width: 700px !important;
        height: 240px;
        background-color: #fefefe !important;
        margin: auto !important;
        padding: 20px !important;
        border: 1px solid #888 !important;
        box-shadow: 0 1px 1px rgba(0,0,0,0.12), 0 2px 2px rgba(0,0,0,0.12), 0 4px 4px rgba(0,0,0,0.12), 0 8px 8px rgba(0,0,0,0.12), 0 16px 16px rgba(0,0,0,0.12) !important;
        border-radius: 10px !important;
    }

    .ui-dialog {
        top: 50% !important;
        left: 50% !important;
        transform: translate(-50%, -50%) !important;
    }


    .ui-widget-header {
        background: none !important;
        padding: 0 !important;
        border: none !important;
    }

    .ui-button {
        background: none !important;
        border: none !important;
    }
</style>

<link href="@Url.Content("~/Content/Clients/plugins/jquery-ui/jquery-ui.css")" rel="stylesheet" type="text/css" />
<script src="@Url.Content("~/Content/Clients/plugins/jquery-ui/jquery-ui.min.js")" type="text/javascript"></script>
<script src="~/Scripts/jquery-3.6.4.min.js"></script>

<script>
    function submitForm() {
        document.getElementById("form-detail-family").submit();
    }

    function CreateDetailFamily(FamilyID) {
        var div = $("#OpenDilog");
        div.load("/DetailFamily/Create?FamilyID=" + FamilyID, function () {
            div.dialog({
                modal: true,
                title: "Thêm Mới Thông Tin",
                resizable: false,
                dialogClass: "my-dialog-class",
                position: 'center',
                show: { effect: 'fade', duration: 400 }
            });
        });
    }

    function EditDetailFamily(DetailFamilyID) {
        var div = $("#OpenDilog");
        div.load("/DetailFamily/Edit?DetailFamilyID=" + DetailFamilyID, function () {
            div.dialog({
                modal: true,
                dialogClass: "my-dialog-class",
                position: 'center',
                show: { effect: 'fade', duration: 400 },
                title: "Chỉnh Sửa Thông Tin",
                resizable: false
            });
        });
    }

    $('body').on('change', '#SelectAll', function () {
        var checkStatus = this.checked;
        var checkbox = $(this).parents('.card-body').find('tr td input:checkbox');
        checkbox.each(function () {
            this.checked = checkStatus;
            if (this.checked) {
                checkbox.attr('selected', 'checked');
            } else {
                checkbox.attr('selected', '');
            }
        });
    });

    $('body').on('click', '#btnDeleteAll', function (e) {
        e.preventDefault();
        var str = "";
        var checkbox = $(this).parents('.card').find('tr td input:checkbox');
        var i = 0;
        checkbox.each(function () {
            if (this.checked) {
                checkbox.attr('selected', 'checked');
                var _id = $(this).val();
                if (i === 0) {
                    str += _id;
                } else {
                    str += "," + _id;
                }
                i++;
            } else {
                checkbox.attr('selected', '');
            }
        });
        if (str.length > 0) {
            var conf = confirm('Bạn có muốn xóa các bản ghi này không ?');
            if (conf === true) {
                $.ajax({
                    url: '/DetailFamily/DeleteAll',
                    type: 'POST',
                    data: { ids: str },
                    success: function (rs) {
                        if (rs.success) {
                            location.reload();
                        }
                    }
                });
            }
        }
    });

</script>

Pagoda/Views/DetailFamily/List.cshtml
@model IEnumerable<Pagoda.Models.DetailFamily>
@{
    ViewBag.Title = "Danh sách chi tiết thành viên gia đình";
    Layout = null;
}

<style>
    .center {
        margin-left: auto;
        margin-right: auto;
    }

    .padding-top-13 td {
        padding-top: 46px;
    }

    .padding-top-29 td {
        padding-top: 46px;
    }
</style>

<div>
    <div>
        <h2 style="text-align: center; margin: 0; font-size: 40px">
            <a style="text-transform: capitalize">Chùa Phụng Sơn</a>
        </h2>

        <br>

        <h2 style="text-align: center; font-size: 18px">
            Tọa lạc ở số 1408, Đường Ba Tháng Hai, Phường 2, Quận 11, Thành phố Hồ Chí Minh, Việt Nam
        </h2>

        <h2 style="text-align: center; font-size: 22px">
            Gia Đình: <a style="text-transform: uppercase ">@ViewBag.FamilyName</a>
        </h2>

        <h2 style="text-align: center; font-size: 22px">
            Địa Chỉ: <a style="text-transform: uppercase">@ViewBag.Address</a>
        </h2>
    </div>

    <div style="display: block">
        <hr style="width: 810px; border: 1px solid black" />
        <h2 style="text-align: center; font-size: 28px; text-transform: capitalize">
            sớ sao cúng hạn
        </h2>
        <hr style="width: 810px; border: 1px solid black" />
    </div>

    <div>
        <table class="center">
            <thead>
                <tr>
                    <th style="width: 90px; text-align: center; font-size: 22px; ">STT</th>
                    <th style="text-align: center; font-size: 22px; width: 140px; ">
                        <a class="text-dark" style=" color: black; text-decoration: none" href="@Url.Action("Index", "DetailFamily", new { sortOrder = ViewBag.FullNameSort, currentFilter = ViewBag.CurrentFilter })">
                            Họ Tên
                        </a>
                    </th>
                    <th style="text-align: center; width: 60px; font-size: 22px; ">
                        Tuổi
                    </th>
                    <th style="text-align: center; width: 110px; font-size: 22px; ">Giới Tính</th>
                    <th style="text-align: center; width: 11px; font-size: 22px; ">Sao</th>
                    <th style="text-align: center; width: 11px; font-size: 22px; ">Hạn</th>
                </tr>
                <tr>
                    <td colspan="12">
                        <hr style="width: 810px; margin: 0; padding: 0" />
                    </td>
                </tr>
            </thead>

            <tbody style="line-height: 51px;">
                @if (Model != null && Model.Any())
                {
                    var i = 1;
                    var count = Model.Count();
                    foreach (var item in Model)
                    {
                        if (i == 13)
                        {
                            <tr id="trow_@item.DetailFamilyID" class="padding-top-13">
                                <td style="text-align: center; font-size: 22px;">@i</td>
                                <td style="text-align: center; font-size: 22px">@item.FullName</td>
                                <td style="text-align: center; font-size: 22px">@item.Age</td>
                                <td style="text-align: center; font-size: 22px">
                                    @if (item.Sex == true)
                                    {@Html.Raw("Nam")}
                                else if (item.Sex == false)
                                { @Html.Raw("Nữ")}
                                </td>
                                <td style="text-align: center; font-size: 22px">@item.Star.StarName</td>
                                <td style="text-align: center; font-size: 22px">@item.Threat.ThreatName</td>
                            </tr>
                            if (i < count)
                            {
                                <tr>
                                    <td colspan="12">
                                        <hr style="width: 810px" />
                                    </td>
                                </tr>
                            }
                        }

                        else if (i == 29)
                        {
                            <tr id="trow_@item.DetailFamilyID" class="padding-top-29">
                                <td style="text-align: center; font-size: 22px;">@i</td>
                                <td style="text-align: center; font-size: 22px">@item.FullName</td>
                                <td style="text-align: center; font-size: 22px">@item.Age</td>
                                <td style="text-align: center; font-size: 22px">
                                    @if (item.Sex == true)
                                    {@Html.Raw("Nam")}
                                else if (item.Sex == false)
                                { @Html.Raw("Nữ")}
                                </td>
                                <td style="text-align: center; font-size: 22px">@item.Star.StarName</td>
                                <td style="text-align: center; font-size: 22px">@item.Threat.ThreatName</td>
                            </tr>
                            if (i < count)
                            {
                                <tr>
                                    <td colspan="12">
                                        <hr style="width: 810px" />
                                    </td>
                                </tr>
                            }
                        }

                        else
                        {
                            <tr id="trow_@item.DetailFamilyID">
                                <td style="text-align: center; font-size: 22px;">@i</td>
                                <td style="text-align: center; font-size: 22px">@item.FullName</td>
                                <td style="text-align: center; font-size: 22px">@item.Age</td>
                                <td style="text-align: center; font-size: 22px">
                                    @if (item.Sex == true)
                                    {@Html.Raw("Nam")}
                                else if (item.Sex == false)
                                { @Html.Raw("Nữ")}
                                </td>
                                <td style="text-align: center; font-size: 22px">@item.Star.StarName</td>
                                <td style="text-align: center; font-size: 22px">@item.Threat.ThreatName</td>
                            </tr>
                            if (i < count)
                            {
                                <tr>
                                    <td colspan="12">
                                        <hr style="width: 810px" />
                                    </td>
                                </tr>
                            }
                        }
                        i++;
                    }
                }
            </tbody>
        </table>
    </div>
</div>