Pagoda/Controllers/FamilyController.cs
using PagedList;
using Pagoda.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using System.Web.UI;
using BoldReports.Linq;
using Pagoda;
using System.Configuration;

namespace Pagoda.Controllers
{
    public class FamilyController : Controller
    {
        [CheckLogin]

        public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page, string familyID)
        {
            string connectionString = ConfigurationManager.ConnectionStrings["PagodaConnectionString1"].ConnectionString;
            PagodaDataContext context = new PagodaDataContext(connectionString);

            ViewBag.CurrentSort = sortOrder;
            ViewBag.FullNameSort = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var families = from s in context.Families select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                families = families.Where(s => s.FamilyName.ToLower().Contains(searchString));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    families = families.OrderByDescending(s => s.FamilyName.Substring(s.FamilyName.LastIndexOf(" ") + 1));
                    break;
                default:  // Name ascending 
                    families = families.OrderBy(s => s.FamilyName.Substring(s.FamilyName.LastIndexOf(" ") + 1));
                    break;
            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(families.ToPagedList(pageNumber, pageSize));
        }


        public ActionResult Create()
        {
            if (Request.Form.Count > 0)
            {
                string familyName = Request.Form["FamilyName"];
                string address = Request.Form["Address"];

                string connectionString = ConfigurationManager.ConnectionStrings["PagodaConnectionString1"].ConnectionString;
                PagodaDataContext context = new PagodaDataContext(connectionString);
                Family family = new Family();

                family.FamilyName = familyName;
                family.Address = address;

                context.Families.InsertOnSubmit(family);
                context.SubmitChanges();
                TempData["Message"] = "Dữ liệu của bạn đã được tạo thành công!!";

                return RedirectToAction("Index");
            }
            return View();
        }

        [CheckPermission]
        public ActionResult Delete(string FamilyID)
        {
            string connectionString = ConfigurationManager.ConnectionStrings["PagodaConnectionString1"].ConnectionString;
            PagodaDataContext context = new PagodaDataContext(connectionString);
            Family family = context.Families.FirstOrDefault(x => x.FamilyID.ToString() == FamilyID);

            context.Families.DeleteOnSubmit(family);
            context.SubmitChanges();
            TempData["Message"] = "Dữ liệu của bạn đã được xóa thành công!!";

            return RedirectToAction("Index");
        }


        public ActionResult Edit(string FamilyID)
        {
            string connectionString = ConfigurationManager.ConnectionStrings["PagodaConnectionString1"].ConnectionString;
            PagodaDataContext context = new PagodaDataContext(connectionString);
            Family family = context.Families.FirstOrDefault(x => x.FamilyID.ToString() == FamilyID);

            if (Request.Form.Count == 0)
            {
                return View(family);
            }

            family.FamilyName = Request.Form["FamilyName"];
            family.Address = Request.Form["Address"];

            context.SubmitChanges();

            TempData["Message"] = "Dữ liệu của bạn đã được cập nhật thành công!!";

            return RedirectToAction("Index");
        }

        public ActionResult List(string sortOrder)
        {
            string connectionString = ConfigurationManager.ConnectionStrings["PagodaConnectionString1"].ConnectionString;
            PagodaDataContext context = new PagodaDataContext(connectionString);

            ViewBag.FullNameSort = String.IsNullOrEmpty(sortOrder) ? "fullname_desc" : "";

            IEnumerable<Family> dsFamily = context.Families.ToList();

            switch (sortOrder)
            {
                case "fullname_desc":
                    dsFamily = dsFamily.OrderByDescending(s => (s.FamilyName).Split().Last());
                    break;
                default:
                    dsFamily = dsFamily.OrderBy(s => (s.FamilyName).Split().Last());
                    break;
            }

            return View(dsFamily);
        }

        public ActionResult PrintPDF()
        {
            var report = new Rotativa.ActionAsPdf("List");
            return report;
        }

        public ActionResult ExportWord()
        {
            string connectionString = ConfigurationManager.ConnectionStrings["PagodaConnectionString1"].ConnectionString;
            PagodaDataContext context = new PagodaDataContext(connectionString);

            var data = context.Families.ToList();
            GridView gridview = new GridView();
            gridview.DataSource = data;
            gridview.DataBind();

            Response.ClearContent();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", "attachment;filename = word.doc");
            Response.ContentType = "application/ms-word";
            Response.Charset = "";

            using (StringWriter sw = new StringWriter())
            {
                using (HtmlTextWriter htw = new HtmlTextWriter(sw))
                {
                    gridview.RenderControl(htw);
                    Response.Output.Write(sw.ToString());
                    Response.Flush();
                    Response.End();
                }
            }
            return View();
        }

        public ActionResult ExportToExcel()
        {
            string connectionString = ConfigurationManager.ConnectionStrings["PagodaConnectionString1"].ConnectionString;
            PagodaDataContext context = new PagodaDataContext(connectionString);

            var gv = new GridView();
            var data = context.Families.ToList();

            gv.DataSource = data;
            gv.DataBind();

            Response.ClearContent();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", "attachment; filename=excel.xls");
            Response.ContentType = "application/ms-excel";

            Response.Charset = "";
            StringWriter objStringWriter = new StringWriter();
            HtmlTextWriter objHtmlTextWriter = new HtmlTextWriter(objStringWriter);

            gv.RenderControl(objHtmlTextWriter);

            Response.Output.Write(objStringWriter.ToString());
            Response.Flush();
            Response.End();

            return View("Index");
        }
    }
}

Pagoda/Controllers/PrayFamilyController.cs
using PagedList;
using Pagoda.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Configuration;

namespace Pagoda.Controllers
{
    public class PrayFamilyController : Controller
    {
        [CheckLogin]

        // GET: PrayFamily
        public ActionResult Index(string keywords, Family family, int? page, string sortOrder, string searchString, string currentFilter)
        {
            string connectionString = ConfigurationManager.ConnectionStrings["PagodaConnectionString1"].ConnectionString;
            PagodaDataContext context = new PagodaDataContext(connectionString);

            IEnumerable<PrayFamily> dsprayFamilies = context.PrayFamilies.Where(x => x.FamilyID == family.FamilyID).ToList();

            string fullname = family.FamilyID.ToString();

            TempData["FamilyID"] = family.FamilyID.ToString();

            ViewBag.fullname = fullname;
            ViewBag.familyName = family.FamilyName;
            ViewBag.CurrentSort = sortOrder;
            ViewBag.FullNameSort = String.IsNullOrEmpty(sortOrder) ? "fullname_desc" : "";
            ViewBag.AgeSort = sortOrder == "Age" ? "age_desc" : "Age";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            if (!String.IsNullOrEmpty(searchString))
            {
                dsprayFamilies = dsprayFamilies.Where(s => s.FullName.ToLower().Contains(searchString.ToLower()));

            };

            switch (sortOrder)
            {
                default:  // Name ascending 
                    dsprayFamilies = dsprayFamilies.OrderBy(s => s.FullName.Substring(s.FullName.LastIndexOf(" ") + 1));
                    break;
            }

            int pageSize = 99999;
            int pageNumber = (page ?? 1);
            return View(dsprayFamilies.ToPagedList(pageNumber, pageSize));
        }


        [HttpGet]
        public PartialViewResult Create()   //Insert PartialView  
        {
            return PartialView(new Pagoda.Models.PrayFamily());
        }


        [HttpPost]
        public JsonResult Create(PrayFamily prayFamily, Family family, string fullFamilyName) // Record Insert  
        {
            string connectionString = ConfigurationManager.ConnectionStrings["PagodaConnectionString1"].ConnectionString;
            PagodaDataContext context = new PagodaDataContext(connectionString);

            fullFamilyName = family.FamilyID.ToString();

            prayFamily.AgeLived = prayFamily.DieDate.Value.Year - prayFamily.BornDate.Value.Year;

            ViewBag.fullFamilyName = fullFamilyName;

            context.PrayFamilies.InsertOnSubmit(prayFamily);
            context.SubmitChanges();

            TempData["Message"] = "Dữ liệu của bạn đã được tạo thành công!!";

            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }

        [CheckPermission]
        public ActionResult Delete(string prayFamilyID)
        {
            string connectionString = ConfigurationManager.ConnectionStrings["PagodaConnectionString1"].ConnectionString;
            PagodaDataContext context = new PagodaDataContext(connectionString);
            PrayFamily prayFamily = context.PrayFamilies.FirstOrDefault(x => x.PrayFamilyID.ToString() == prayFamilyID);

            context.PrayFamilies.DeleteOnSubmit(prayFamily);
            context.SubmitChanges();
            TempData["Message"] = "Dữ liệu của bạn đã được xóa thành công!!";

            Family family = new Family();

            return RedirectToAction("Index", new { FamilyID = prayFamily.FamilyID.ToString() });
        }

        [CheckPermission]
        [HttpPost]
        public ActionResult DeleteAll(string ids)
        {
            string connectionString = ConfigurationManager.ConnectionStrings["PagodaConnectionString1"].ConnectionString;
            PagodaDataContext context = new PagodaDataContext(connectionString);
            if (!string.IsNullOrEmpty(ids))
            {
                var items = ids.Split(',').Select(x => Convert.ToInt32(x)).ToList();
                if (items != null && items.Any())
                {
                    var PrayFamilyToDelete = context.PrayFamilies.Where(x => items.Contains(x.PrayFamilyID)).ToList();
                    context.PrayFamilies.DeleteAllOnSubmit(PrayFamilyToDelete);
                    TempData["Message"] = "Tất Cả dữ liệu của bạn đã được xóa thành công!!";
                    context.SubmitChanges();
                }
                return Json(new { success = true });
            }
            return Json(new { success = false });
        }


        [HttpGet]
        public PartialViewResult Edit(Int32 prayFamilyID)  // Update PartialView  
        {
            string connectionString = ConfigurationManager.ConnectionStrings["PagodaConnectionString1"].ConnectionString;
            PagodaDataContext context = new PagodaDataContext(connectionString);
            PrayFamily prayFamily = context.PrayFamilies.Where(x => x.PrayFamilyID == prayFamilyID).FirstOrDefault();
            PrayFamily prayFamilys = new PrayFamily();

            prayFamilys.PrayFamilyID = prayFamily.PrayFamilyID;
            prayFamilys.FullName = prayFamily.FullName;
            prayFamilys.Sex = prayFamily.Sex;
            prayFamilys.AgeLived = prayFamily.AgeLived;
            prayFamilys.DieDate = prayFamily.DieDate;
            prayFamilys.BornDate = prayFamily.BornDate;
            prayFamilys.WhereDie = prayFamily.WhereDie;
            prayFamilys.WhereBorn = prayFamily.WhereBorn;

            return PartialView(prayFamilys);
        }


        [HttpPost]
        public JsonResult Edit(PrayFamily prayFamily, Family family, string fullFamilyName)
        {
            string connectionString = ConfigurationManager.ConnectionStrings["PagodaConnectionString1"].ConnectionString;
            PagodaDataContext context = new PagodaDataContext(connectionString);
            PrayFamily pf = context.PrayFamilies.Where(x => x.PrayFamilyID == prayFamily.PrayFamilyID).FirstOrDefault();

            fullFamilyName = family.FamilyID.ToString();

            ViewBag.fullFamilyName = fullFamilyName;

            pf.FullName = prayFamily.FullName;
            pf.Sex = prayFamily.Sex;
            pf.DieDate = prayFamily.DieDate;
            pf.BornDate = prayFamily.BornDate;
            pf.WhereBorn = prayFamily.WhereBorn;
            pf.WhereDie = prayFamily.WhereDie;

            if (pf.BornDate.HasValue && pf.DieDate.HasValue)
            {
                pf.AgeLived = pf.DieDate.Value.Year - pf.BornDate.Value.Year;
            }
            else
            {
                pf.AgeLived = 0;
            }
            context.SubmitChanges();
            TempData["Message"] = "Dữ liệu của bạn đã được cập nhật thành công!!";
            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult List(int? familyID, Family family, string sortOrder)
        {
            string connectionString = ConfigurationManager.ConnectionStrings["PagodaConnectionString1"].ConnectionString;
            PagodaDataContext context = new PagodaDataContext(connectionString);

            IEnumerable<PrayFamily> dsPrayFamilies = context.PrayFamilies.Where(x => x.FamilyID == familyID).ToList();

            if (familyID == null)
            {
                return RedirectToAction("Index", "Home");
            }

            ViewBag.FamilyName = context.Families.FirstOrDefault(x => x.FamilyID == familyID)?.FamilyName;

            ViewBag.Address = context.Families.FirstOrDefault(x => x.FamilyID == familyID)?.Address;

            switch (sortOrder)
            {
                default:  // Name ascending 
                    dsPrayFamilies = dsPrayFamilies.OrderBy(s => s.FullName.Substring(s.FullName.LastIndexOf(" ") + 1));
                    break;
            }

            ViewBag.fullname = familyID;

            return View(dsPrayFamilies);
        }

        public ActionResult PrintPDF(int? familyID, Family family)
        {
            if (familyID == null)
            {
                return RedirectToAction("Index", "Home");
            }

            var report = new Rotativa.ActionAsPdf("List", new { familyID = familyID, familyName = ViewBag.FamilyName })
            {
                PageMargins = { Left = 20, Bottom = 18, Right = 20, Top = 18 },
                PageSize = Rotativa.Options.Size.A4,
            };
            return report;
        }

    }
}

Pagoda/Views/Family/Create.cshtml
@model Pagoda.Models.Family

@*@{
        ViewBag.Title = "Create";
        Layout = "~/Views/Shared/_Layout.cshtml";
    }*@

@{
    Layout = null;
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="text-bold mb-2">Tên Gia Đình</div>
            <div class="col-md-12">
                @Html.EditorFor(model => model.FamilyName, new { htmlAttributes = new { @class = "form-control", placeholder = "Xin Mời Nhập Tên Gia Đình" } })
                @Html.ValidationMessageFor(model => model.FamilyName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="text-bold mb-2">Địa Chỉ</div>
            <div class="col-md-12">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control", placeholder = "Xin Mời Nhập Địa Chỉ" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10 text-right" style="margin-left: 68px;">
                <input type="submit" value="Lưu" class="btn btn-danger" />
            </div>
        </div>
    </div>
}

<link href="@Url.Content("~/Content/Clients/plugins/jquery-ui/jquery-ui.css")" rel="stylesheet" type="text/css" />
<script src="@Url.Content("~/Content/Clients/plugins/jquery-ui/jquery-ui.min.js")" type="text/javascript"></script>

Pagoda/Views/Family/Edit.cshtml
@model Pagoda.Models.Family

@*@{
        ViewBag.Title = "Edit";
        Layout = "~/Views/Shared/_Layout.cshtml";
    }*@

@{
    ViewBag.Title = "Edit";
    Layout = null;
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.FamilyID)

        <div class="form-group">
            <div class="text-bold mb-2">Họ Tên</div>
            <div class="col-md-12">
                @Html.EditorFor(model => model.FamilyName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FamilyName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="text-bold mb-2">Địa Chỉ</div>
            <div class="col-md-12">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10 text-right" style="margin-left: 68px;">
                <input type="submit" value="Lưu" class="btn btn-danger" />
            </div>
        </div>
    </div>
}

<link href="@Url.Content("~/Content/Clients/plugins/jquery-ui/jquery-ui.css")" rel="stylesheet" type="text/css" />
<script src="@Url.Content("~/Content/Clients/plugins/jquery-ui/jquery-ui.min.js")" type="text/javascript"></script>

Pagoda/Views/Family/Index.cshtml
@model PagedList.PagedList<Pagoda.Models.Family>
@using PagedList.Mvc;
@using PagedList;

@{
    ViewBag.Title = "Danh Sách Gia Đình Đi Lễ";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section naviheader{
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
    </ul>
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Quản Lý Gia Đình</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/">Trang Chủ</a></li>
                    <li class="breadcrumb-item active">@ViewBag.Title</li>
                </ol>
            </div>
        </div>
        <div class="row mb-2">
            <div class="col-sm-8">
                <form class="form-inline">
                    @using (Html.BeginForm("Index", "Family", FormMethod.Get))
                    {
                        @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control", @id = "Search", placeholder = "Nhập tên hộ gia đình cần tìm kiếm ...", @style = "max-width: 500px; width: 60%" })
                        <button class="btn btn-info ml-1" type="submit">Tìm kiếm</button>
                    }
                </form>
            </div>

            <div align="right" class="col-sm-4">
                <div class="btn-group mr-1">
                    @Html.ActionLink("In Danh Sách", "PrintPDF", null, new { @class = "btn", @style = "float: right; color: white; background-color: #6600FF" })
                </div>
                <button class="btn mr-1" style="float: right; background-color: #CD853F; color: white" type="button" onclick="window.location.href='/Family'">
                    Làm Mới Danh Sách
                </button>
            </div>

        </div>
    </div><!-- /.container-fluid -->
</section>

@if (TempData["Message"] != null)
{
    <div class="alert alert-default-info" style="margin-left: 8px; margin-right: 8px">
        @TempData["Message"]
        <button type="button" class="close" data-dismiss="alert">
            <span>
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="25" style="vertical-align: unset" fill="currentColor" class="bi bi-x-circle-fill" viewBox="0 0 16 16">
                    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM5.354 4.646a.5.5 0 1 0-.708.708L7.293 8l-2.647 2.646a.5.5 0 0 0 .708.708L8 8.707l2.646 2.647a.5.5 0 0 0 .708-.708L8.707 8l2.647-2.646a.5.5 0 0 0-.708-.708L8 7.293 5.354 4.646z" />
                </svg>
            </span>
        </button>
    </div>
}

<div id="OpenDilog">

</div>

<section class="content">
    <!-- Default box -->
    <div class="card">
        <div class="card-header" style="position: relative;">
            <h3 class="card-title" style="position: absolute; top: 35%;">@ViewBag.Title</h3>

            <div class="card-tools">
                <a href="#" class="btn" style="background-color: #000066; color: white" onclick="CreateFamily()">
                    Thêm Mới
                </a>
                @*<a href="#" class="btn btn-danger" id="btnDeleteAll">Xóa Tất Cả</a>*@
            </div>
        </div>
        <div class="card-body">
            <table class="table table-hover tblData" id="headerTable">
                <thead>
                    <tr>
                        <th style="text-align: center">STT</th>
                        <th style="text-align: center">
                            <a class="text-dark" href="@Url.Action("Index", "Family", new { sortOrder = ViewBag.FullNameSort, currentFilter = ViewBag.CurrentFilter })">
                                Gia Đình
                                <svg xmlns="http://www.w3.org/2000/svg" style="vertical-align: unset; padding-top: 5px" width="12" height="16" fill="currentColor" class="bi bi-arrow-down-up" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd" d="M11.5 15a.5.5 0 0 0 .5-.5V2.707l3.146 3.147a.5.5 0 0 0 .708-.708l-4-4a.5.5 0 0 0-.708 0l-4 4a.5.5 0 1 0 .708.708L11 2.707V14.5a.5.5 0 0 0 .5.5zm-7-14a.5.5 0 0 1 .5.5v11.793l3.146-3.147a.5.5 0 0 1 .708.708l-4 4a.5.5 0 0 1-.708 0l-4-4a.5.5 0 0 1 .708-.708L4 13.293V1.5a.5.5 0 0 1 .5-.5z" />
                                </svg>
                            </a>
                        </th>
                        <th style="text-align: center">Địa Chỉ</th>
                        <th style="text-align: center">Hành Động</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null && Model.Any())
                    {
                        var i = 1;
                        foreach (var item in Model)
                        {
                            <tr id="trow_@item.FamilyID" class="Search">
                                <td style="text-align: center">@i</td>

                                <td style="text-align: center">@item.FamilyName</td>
                                <td style="text-align: center">@item.Address</td>

                                <td style="text-align: center; display: flex; margin-left: 74px">
                                    <a href="#" class="btn btn-sm btn-success" style="margin-right: 3px" onclick="EditFamily('@item.FamilyID')">
                                        Chỉnh Sửa
                                    </a>

                                    <div class="dropdown">
                                        <button class="btn btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false" style="margin-right: 3px; color: white; background-color: #528B8B; border-color: #528B8B ">
                                            Chi Tiết
                                        </button>
                                        <div class="dropdown-menu">
                                            @using (Html.BeginForm("Index", "DetailFamily", FormMethod.Post))
                                            {
                                                @Html.Hidden("FamilyID", item.FamilyID)
                                                @Html.Hidden("FamilyName", item.FamilyName)
                                                @Html.Hidden("FamilyAddress", item.Address)
                                                <button type="submit" class="btn btn-sm btn-success dropdown-item">Quản Lý Cầu An</button>
                                            }

                                            @using (Html.BeginForm("Index", "PrayFamily", FormMethod.Post))
                                            {
                                                @Html.Hidden("FamilyID", item.FamilyID)
                                                @Html.Hidden("FamilyName", item.FamilyName)
                                                <button type="submit" class="btn btn-sm btn-success dropdown-item">Quản Lý Cầu Siêu</button>
                                            }
                                        </div>
                                    </div>
                                    @if (Session["MaNhomSession"].ToString() == "1")
                                    {

                                    @Html.ActionLink("Xóa", "Delete", new { FamilyID = item.FamilyID }, new { @class = "btn btn-sm btn-warning", onclick = "return confirm('Bạn có chắc chắn muốn xóa không?');" })
                                    }

                                </td>
                            </tr>
                            i++;
                        }
                    }

                    else
                    {
                        <tr>
                            <td colspan="12">Không có bản ghi nào!!!</td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                    }
                </tbody>
            </table>

            <div class="row text-center">
                <div class="col-12">
                    @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
                </div>
            </div>
        </div>
    </div>
</section>

<style>
    .my-dialog-class {
        width: 480px !important;
        height: 240px;
        background-color: #fefefe !important;
        margin: auto !important;
        padding: 20px !important;
        border: 1px solid #888 !important;
        box-shadow: 0 1px 1px rgba(0,0,0,0.12), 0 2px 2px rgba(0,0,0,0.12), 0 4px 4px rgba(0,0,0,0.12), 0 8px 8px rgba(0,0,0,0.12), 0 16px 16px rgba(0,0,0,0.12) !important;
        border-radius: 10px !important;
    }

    .ui-widget-header {
        background: none !important;
        padding: 0 !important;
        border: none !important;
    }

    .ui-dialog {
        top: 50% !important;
        left: 50% !important;
        transform: translate(-50%, -50%) !important;
    }

    .ui-button {
        background: none !important;
        border: none !important;
    }
</style>

<link href="~/Content/MyDialog.css" rel="stylesheet" />
<link href="@Url.Content("~/Content/Clients/plugins/jquery-ui/jquery-ui.css")" rel="stylesheet" type="text/css" />
<script src="@Url.Content("~/Content/Clients/plugins/jquery-ui/jquery-ui.min.js")" type="text/javascript"></script>

<script type="text/javascript">

    function CreateFamily() {
        var div = $("#OpenDilog");
        div.load("/Family/Create", function () {
            div.dialog({
                modal: true,
                title: "Thêm Mới Thông Tin",
                resizable: false,
                position: 'center',
                show: { effect: 'fade', duration: 400 },
                dialogClass: "my-dialog-class",
            });
        });
    }

    function EditFamily(FamilyID) {
        var div = $("#OpenDilog");
        div.load("/Family/Edit?FamilyID=" + FamilyID, function () {
            div.dialog({
                modal: true,
                dialogClass: "my-dialog-class",
                position: 'center',
                show: { effect: 'fade', duration: 400 },
                title: "Chỉnh Sửa Thông Tin",
                resizable: false
            });
        });
    }

</script>